export const sp500StockList = [
  { name: "Apple Inc.", symbol: "AAPL" },
  { name: "Nvidia Corp", symbol: "NVDA" },
  { name: "Microsoft Corp", symbol: "MSFT" },
  { name: "Amazon.com Inc", symbol: "AMZN" },
  { name: "Meta Platforms, Inc. Class A", symbol: "META" },
  { name: "Alphabet Inc. Class A", symbol: "GOOGL" },
  { name: "Tesla, Inc.", symbol: "TSLA" },
  { name: "Broadcom Inc.", symbol: "AVGO" },
  { name: "Alphabet Inc. Class C", symbol: "GOOG" },
  { name: "Berkshire Hathaway Class B", symbol: "BRK.B" },
  { name: "Jpmorgan Chase & Co.", symbol: "JPM" },
  { name: "Eli Lilly & Co.", symbol: "LLY" },
  { name: "Visa Inc.", symbol: "V" },
  { name: "Unitedhealth Group Incorporated", symbol: "UNH" },
  { name: "Exxon Mobil Corporation", symbol: "XOM" },
  { name: "Mastercard Incorporated", symbol: "MA" },
  { name: "Costco Wholesale Corp", symbol: "COST" },
  { name: "Walmart Inc.", symbol: "WMT" },
  { name: "Home Depot, Inc.", symbol: "HD" },
  { name: "Procter & Gamble Company", symbol: "PG" },
  { name: "Netflix Inc", symbol: "NFLX" },
  { name: "Johnson & Johnson", symbol: "JNJ" },
  { name: "Salesforce, Inc.", symbol: "CRM" },
  { name: "Abbvie Inc.", symbol: "ABBV" },
  { name: "Bank of America Corporation", symbol: "BAC" },
  { name: "Chevron Corporation", symbol: "CVX" },
  { name: "Merck & Co., Inc.", symbol: "MRK" },
  { name: "Oracle Corp", symbol: "ORCL" },
  { name: "Coca-Cola Company", symbol: "KO" },
  { name: "Wells Fargo & Co.", symbol: "WFC" },
  { name: "Cisco Systems, Inc.", symbol: "CSCO" },
  { name: "Accenture Plc", symbol: "ACN" },
  { name: "Thermo Fisher Scientific, Inc.", symbol: "TMO" },
  { name: "Servicenow, Inc.", symbol: "NOW" },
  { name: "Linde Plc", symbol: "LIN" },
  { name: "Mcdonald's Corporation", symbol: "MCD" },
  { name: "International Business Machines Corporation", symbol: "IBM" },
  { name: "Pepsico, Inc.", symbol: "PEP" },
  { name: "The Walt Disney Company", symbol: "DIS" },
  { name: "Abbott Laboratories", symbol: "ABT" },
  { name: "Intuitive Surgical Inc.", symbol: "ISRG" },
  { name: "Ge Aerospace", symbol: "GE" },
  { name: "Advanced Micro Devices", symbol: "AMD" },
  { name: "Philip Morris International Inc.", symbol: "PM" },
  { name: "Adobe Inc.", symbol: "ADBE" },
  { name: "Goldman Sachs Group Inc.", symbol: "GS" },
  { name: "Caterpillar Inc.", symbol: "CAT" },
  { name: "Qualcomm Inc", symbol: "QCOM" },
  { name: "Texas Instruments Incorporated", symbol: "TXN" },
  { name: "Intuit Inc", symbol: "INTU" },
  { name: "American Express Company", symbol: "AXP" },
  { name: "Verizon Communications", symbol: "VZ" },
  { name: "Rtx Corporation", symbol: "RTX" },
  { name: "Booking Holdings Inc.", symbol: "BKNG" },
  { name: "At&t Inc.", symbol: "T" },
  { name: "Morgan Stanley", symbol: "MS" },
  { name: "S&p Global Inc.", symbol: "SPGI" },
  { name: "Danaher Corporation", symbol: "DHR" },
  { name: "Pfizer Inc.", symbol: "PFE" },
  { name: "Amgen Inc", symbol: "AMGN" },
  { name: "Applied Materials Inc", symbol: "AMAT" },
  { name: "Lowe's Companies Inc.", symbol: "LOW" },
  { name: "Honeywell International, Inc.", symbol: "HON" },
  { name: "Boston Scientific Corp.", symbol: "BSX" },
  { name: "Progressive Corporation", symbol: "PGR" },
  { name: "Blackrock, Inc.", symbol: "BLK" },
  { name: "Nextra Energy, Inc.", symbol: "NEE" },
  { name: "Union Pacific Corp.", symbol: "UNP" },
  { name: "Citigroup Inc.", symbol: "C" },
  { name: "Comcast Corp", symbol: "CMCSA" },
  { name: "Uber Technologies, Inc.", symbol: "UBER" },
  { name: "Conocophillips", symbol: "COP" },
  { name: "Palantir Technologies Inc. Class A", symbol: "PLTR" },
  { name: "Tjx Companies, Inc.", symbol: "TJX" },
  { name: "Eaton Corporation, Plcs", symbol: "ETN" },
  { name: "Boeing Company", symbol: "BA" },
  { name: "Stryker Corporation", symbol: "SYK" },
  { name: "Blackstone Inc.", symbol: "BX" },
  { name: "Automatic Data Processing", symbol: "ADP" },
  { name: "Arista Networks", symbol: "ANET" },
  { name: "Fiserv, Inc.", symbol: "FI" },
  { name: "Gilead Sciences Inc", symbol: "GILD" },
  { name: "Bristol-Myers Squibb Co.", symbol: "BMY" },
  { name: "Palo Alto Networks, Inc.", symbol: "PANW" },
  { name: "Deere & Company", symbol: "DE" },
  { name: "Medtronic Plc", symbol: "MDT" },
  { name: "The Charles Schwab Corporation", symbol: "SCHW" },
  { name: "Micron Technology, Inc.", symbol: "MU" },
  { name: "Analog Devices, Inc.", symbol: "ADI" },
  { name: "Vertex Pharmaceuticals Inc", symbol: "VRTX" },
  { name: "Starbucks Corp", symbol: "SBUX" },
  { name: "Ge Vernova Inc.", symbol: "GEV" },
  { name: "Marsh & Mclennan Companies, Inc.", symbol: "MMC" },
  { name: "T-Mobile Us, Inc.", symbol: "TMUS" },
  { name: "Lockheed Martin Corp.", symbol: "LMT" },
  { name: "Prologis, Inc.", symbol: "PLD" },
  { name: "Chubb Limited", symbol: "CB" },
  { name: "Kkr & Co. Inc.", symbol: "KKR" },
  { name: "Lam Research Corp", symbol: "LRCX" },
  { name: "Kla Corporation", symbol: "KLAC" },
  { name: "United Parcel Service, Inc. Class B", symbol: "UPS" },
  { name: "Elevance Health, Inc.", symbol: "ELV" },
  { name: "Constellation Energy Corporation", symbol: "CEG" },
  { name: "The Southern Company", symbol: "SO" },
  { name: "Paypal Holdings, Inc.", symbol: "PYPL" },
  { name: "Altria Group, Inc.", symbol: "MO" },
  { name: "Equinix, Inc. Reit", symbol: "EQIX" },
  { name: "Trane Technologies Plc", symbol: "TT" },
  { name: "Nike, Inc.", symbol: "NKE" },
  { name: "Amphenol Corporation", symbol: "APH" },
  { name: "American Tower Corporation", symbol: "AMT" },
  { name: "Cme Group Inc.", symbol: "CME" },
  { name: "Intercontinental Exchange Inc.", symbol: "ICE" },
  { name: "Parker-Hannifin Corporation", symbol: "PH" },
  { name: "Intel Corp", symbol: "INTC" },
  { name: "Duke Energy Corporation", symbol: "DUK" },
  { name: "Crowdstrike Holdings, Inc. Class A", symbol: "CRWD" },
  { name: "Cadence Design Systems", symbol: "CDNS" },
  { name: "The Cigna Group", symbol: "CI" },
  { name: "The Sherwin-Williams Company", symbol: "SHW" },
  { name: "Aon Plc Class A", symbol: "AON" },
  { name: "Pnc Financial Services Group", symbol: "PNC" },
  { name: "Motorola Solutions, Inc.", symbol: "MSI" },
  { name: "Chipotle Mexican Grill, Inc.", symbol: "CMG" },
  { name: "U.S. Bancorp", symbol: "USB" },
  { name: "Eog Resources, Inc.", symbol: "EOG" },
  { name: "Mondelez International, Inc. Class A", symbol: "MDLZ" },
  { name: "Waste Management, Inc.", symbol: "WM" },
  { name: "Mckesson Corporation", symbol: "MCK" },
  { name: "Synopsys Inc", symbol: "SNPS" },
  { name: "Welltower Inc.", symbol: "WELL" },
  { name: "3m Company", symbol: "MMM" },
  { name: "Zoetis Inc.", symbol: "ZTS" },
  { name: "Transdigm Group Incorporated", symbol: "TDG" },
  { name: "Regeneron Pharmaceuticals Inc", symbol: "REGN" },
  { name: "Arthur J. Gallagher & Co.", symbol: "AJG" },
  { name: "Moody's Corporation", symbol: "MCO" },
  { name: "Colgate-Palmolive Company", symbol: "CL" },
  { name: "Apollo Global Management, Inc.", symbol: "APO" },
  { name: "Williams Companies Inc.", symbol: "WMB" },
  { name: "Capital One Financial", symbol: "COF" },
  { name: "O'reilly Automotive, Inc.", symbol: "ORLY" },
  { name: "Air Products & Chemicals, Inc.", symbol: "APD" },
  { name: "General Dynamics Corporation", symbol: "GD" },
  { name: "Emerson Electric Co.", symbol: "EMR" },
  { name: "Becton, Dickinson and Co.", symbol: "BDX" },
  { name: "Illinois Tool Works Inc.", symbol: "ITW" },
  { name: "Cintas Corp", symbol: "CTAS" },
  { name: "Northrop Grumman Corp.", symbol: "NOC" },
  { name: "Cvs Health Corporation", symbol: "CVS" },
  { name: "Marriot International Class A", symbol: "MAR" },
  { name: "Target Corporation", symbol: "TGT" },
  { name: "Fedex Corporation", symbol: "FDX" },
  { name: "Csx Corporation", symbol: "CSX" },
  { name: "Oneok, Inc.", symbol: "OKE" },
  { name: "Autodesk Inc", symbol: "ADSK" },
  { name: "Hilton Worldwide Holdings Inc.", symbol: "HLT" },
  { name: "Ecolab, Inc.", symbol: "ECL" },
  { name: "Fortinet, Inc.", symbol: "FTNT" },
  { name: "Truist Financial Corporation", symbol: "TFC" },
  { name: "Vistra Corp.", symbol: "VST" },
  { name: "Paccar Inc", symbol: "PCAR" },
  { name: "Carrier Global Corporation", symbol: "CARR" },
  { name: "Royal Caribbean Group", symbol: "RCL" },
  { name: "Freeport-Mcmoran Inc.", symbol: "FCX" },
  { name: "Schlumberger Limited", symbol: "SLB" },
  { name: "Kinder Morgan, Inc.", symbol: "KMI" },
  { name: "General Motors Company", symbol: "GM" },
  { name: "Hca Healthcare, Inc.", symbol: "HCA" },
  { name: "Airbnb, Inc. Class A", symbol: "ABNB" },
  { name: "Bank of New York Mellon Corporation", symbol: "BK" },
  { name: "Roper Technologies, Inc.", symbol: "ROP" },
  { name: "Autozone, Inc.", symbol: "AZO" },
  { name: "Digital Realty Trust, Inc.", symbol: "DLR" },
  { name: "Norfolk Southern Corp.", symbol: "NSC" },
  { name: "The Travelers Companies, Inc.", symbol: "TRV" },
  { name: "Johnson Controls International Plc", symbol: "JCI" },
  { name: "Nxp Semiconductors N.v.", symbol: "NXPI" },
  { name: "Simon Property Group, Inc.", symbol: "SPG" },
  { name: "Workday, Inc. Class A", symbol: "WDAY" },
  { name: "Aflac Inc.", symbol: "AFL" },
  { name: "Ameriprise Financial, Inc.", symbol: "AMP" },
  { name: "American Electric Power Company, Inc.", symbol: "AEP" },
  { name: "Cummins Inc.", symbol: "CMI" },
  { name: "Ross Stores Inc", symbol: "ROST" },
  { name: "The Allstate Corporation", symbol: "ALL" },
  { name: "Sempra", symbol: "SRE" },
  { name: "Copart Inc", symbol: "CPRT" },
  { name: "Metlife, Inc.", symbol: "MET" },
  { name: "Phillips 66", symbol: "PSX" },
  { name: "Howmet Aerospace Inc.", symbol: "HWM" },
  { name: "W.W. Grainger, Inc.", symbol: "GWW" },
  { name: "Marathon Petroleum Corporation", symbol: "MPC" },
  { name: "United Rentals, Inc.", symbol: "URI" },
  { name: "Fair Isaac Corporation", symbol: "FICO" },
  { name: "Quanta Services, Inc.", symbol: "PWR" },
  { name: "Realty Income Corporation", symbol: "O" },
  { name: "Msci, Inc.", symbol: "MSCI" },
  { name: "Newmont Corporation", symbol: "NEM" },
  { name: "Public Storage", symbol: "PSA" },
  { name: "Discover Financial Services", symbol: "DFS" },
  { name: "Paychex Inc", symbol: "PAYX" },
  { name: "American International Group, Inc.", symbol: "AIG" },
  { name: "Dominion Energy, Inc", symbol: "D" },
  { name: "Baker Hughes Company", symbol: "BKR" },
  { name: "Targa Resources Corp.", symbol: "TRGP" },
  { name: "Lululemon Athletica Inc.", symbol: "LULU" },
  { name: "Te Connectivity Plc", symbol: "TEL" },
  { name: "Delta Air Lines, Inc.", symbol: "DAL" },
  { name: "Valero Energy Corporation", symbol: "VLO" },
  { name: "Public Service Enterprise Group Incorporated", symbol: "PEG" },
  { name: "Fastenal Co", symbol: "FAST" },
  { name: "Fidelity National Information Services, Inc.", symbol: "FIS" },
  { name: "Republic Services Inc.", symbol: "RSG" },
  { name: "Kimberly-Clark Corp.", symbol: "KMB" },
  { name: "Axon Enterprise, Inc.", symbol: "AXON" },
  { name: "Cencora, Inc.", symbol: "COR" },
  { name: "Edwards Lifesciences Corp", symbol: "EW" },
  { name: "Prudential Financial, Inc.", symbol: "PRU" },
  { name: "Corteva, Inc.", symbol: "CTVA" },
  { name: "D.R. Horton Inc.", symbol: "DHI" },
  { name: "Ametek, Inc.", symbol: "AME" },
  { name: "Agilent Technologies Inc.", symbol: "A" },
  { name: "L3harris Technologies, Inc.", symbol: "LHX" },
  { name: "Hess Corporation", symbol: "HES" },
  { name: "Kenvue Inc.", symbol: "KVUE" },
  { name: "The Kroger Co.", symbol: "KR" },
  { name: "Verisk Analytics, Inc.", symbol: "VRSK" },
  { name: "Gartner, Inc.", symbol: "IT" },
  { name: "Ge Healthcare Technologies Inc.", symbol: "GEHC" },
  { name: "Cognizant Technology Solutions", symbol: "CTSH" },
  { name: "Ford Motor Company", symbol: "F" },
  { name: "Exelon Corporation", symbol: "EXC" },
  { name: "Crown Castle Inc.", symbol: "CCI" },
  { name: "Cbre Group, Inc.", symbol: "CBRE" },
  { name: "Xcel Energy, Inc.", symbol: "XEL" },
  { name: "Otis Worldwide Corporation", symbol: "OTIS" },
  { name: "Corning Incorporated", symbol: "GLW" },
  { name: "Sysco Corporation", symbol: "SYY" },
  { name: "Ingersoll Rand Inc.", symbol: "IR" },
  { name: "Pg&e Corporation", symbol: "PCG" },
  { name: "United Airlines Holdings, Inc.", symbol: "UAL" },
  { name: "Occidental Petroleum Corporation", symbol: "OXY" },
  { name: "Monster Beverage Corporation", symbol: "MNST" },
  { name: "Keurig Dr Pepper Inc.", symbol: "KDP" },
  { name: "Yum! Brands, Inc.", symbol: "YUM" },
  { name: "Old Dominion Freight Line", symbol: "ODFL" },
  { name: "Arch Capital Group Ltd", symbol: "ACGL" },
  { name: "Vulcan Materials Company", symbol: "VMC" },
  { name: "Idexx Laboratories Inc", symbol: "IDXX" },
  { name: "Iqvia Holdings Inc.", symbol: "IQV" },
  { name: "Wabtec Inc.", symbol: "WAB" },
  { name: "Humana Inc.", symbol: "HUM" },
  { name: "Electronic Arts Inc", symbol: "EA" },
  { name: "Resmed Inc.", symbol: "RMD" },
  { name: "Dell Technologies Inc.", symbol: "DELL" },
  { name: "Charter Comm Inc Del Cl a", symbol: "CHTR" },
  { name: "Entergy Corporation", symbol: "ETR" },
  { name: "Diamondback Energy, Inc.", symbol: "FANG" },
  { name: "General Mills, Inc.", symbol: "GIS" },
  { name: "Garmin Ltd", symbol: "GRMN" },
  { name: "M&t Bank Corp.", symbol: "MTB" },
  { name: "Lennar Corporation Class A", symbol: "LEN" },
  { name: "Centene Corporation", symbol: "CNC" },
  { name: "The Hartford Financial Services Group, Inc.", symbol: "HIG" },
  { name: "Martin Marietta Materials", symbol: "MLM" },
  { name: "Nasdaq, Inc.", symbol: "NDAQ" },
  { name: "Extra Space Storage, Inc.", symbol: "EXR" },
  { name: "Willis Towers Watson Public Limited Companys", symbol: "WTW" },
  { name: "Dupont De Nemours, Inc.", symbol: "DD" },
  { name: "Hp Inc.", symbol: "HPQ" },
  { name: "Deckers Outdoor Corp", symbol: "DECK" },
  { name: "Equifax, Incorporated", symbol: "EFX" },
  { name: "Rockwell Automation, Inc.", symbol: "ROK" },
  { name: "Avalonbay Communities, Inc.", symbol: "AVB" },
  { name: "Consolidated Edison, Inc.", symbol: "ED" },
  { name: "Dexcom, Inc.", symbol: "DXCM" },
  { name: "Ebay Inc", symbol: "EBAY" },
  { name: "Microchip Technology Inc", symbol: "MCHP" },
  { name: "Vici Properties Inc.", symbol: "VICI" },
  { name: "Iron Mountain Inc.", symbol: "IRM" },
  { name: "Eqt Corp", symbol: "EQT" },
  { name: "Cardinal Health, Inc.", symbol: "CAH" },
  { name: "Wec Energy Group, Inc.", symbol: "WEC" },
  { name: "Ansys Inc", symbol: "ANSS" },
  { name: "Take-Two Interactive Software Inc", symbol: "TTWO" },
  { name: "Hewlett Packard Enterprise Company", symbol: "HPE" },
  { name: "Monolithic Power Systems, Inc.", symbol: "MPWR" },
  { name: "Fifth Third Bancorp", symbol: "FITB" },
  { name: "Raymond James Financial, Inc.", symbol: "RJF" },
  { name: "Nucor Corporation", symbol: "NUE" },
  { name: "Costar Group Inc", symbol: "CSGP" },
  { name: "Keysight Technologies, Inc.", symbol: "KEYS" },
  { name: "Constellation Brands, Inc.", symbol: "STZ" },
  { name: "Tractor Supply Co", symbol: "TSCO" },
  { name: "Dow Inc.", symbol: "DOW" },
  { name: "Xylem Inc", symbol: "XYL" },
  { name: "State Street Corporation", symbol: "STT" },
  { name: "Godaddy Inc", symbol: "GDDY" },
  { name: "Global Payments, Inc.", symbol: "GPN" },
  { name: "Ppg Industries, Inc.", symbol: "PPG" },
  { name: "Fortive Corporation", symbol: "FTV" },
  { name: "Mettler-Toledo International", symbol: "MTD" },
  { name: "Broadridge Financial Solutions Inc", symbol: "BR" },
  { name: "Smurfit Westrock Plc", symbol: "SW" },
  { name: "Dover Corporation", symbol: "DOV" },
  { name: "Church & Dwight Co., Inc.", symbol: "CHD" },
  { name: "Synchrony Financial", symbol: "SYF" },
  { name: "Carnival Corporation", symbol: "CCL" },
  { name: "The Kraft Heinz Company", symbol: "KHC" },
  { name: "Veralto Corporation", symbol: "VLTO" },
  { name: "Nvr, Inc.", symbol: "NVR" },
  { name: "Texas Pacific Land Corporation", symbol: "TPL" },
  { name: "Corpay, Inc.", symbol: "CPAY" },
  { name: "T Rowe Price Group Inc", symbol: "TROW" },
  { name: "Cdw Corporation", symbol: "CDW" },
  { name: "Halliburton Company", symbol: "HAL" },
  { name: "Dte Energy Company", symbol: "DTE" },
  { name: "Brown & Brown, Inc.", symbol: "BRO" },
  { name: "Archer Daniels Midland Company", symbol: "ADM" },
  { name: "Devon Energy Corporation", symbol: "DVN" },
  { name: "Tyler Technologies, Inc.", symbol: "TYL" },
  { name: "Ventas, Inc.", symbol: "VTR" },
  { name: "Huntington Bancshares Inc", symbol: "HBAN" },
  { name: "Waters Corp", symbol: "WAT" },
  { name: "Equity Residential", symbol: "EQR" },
  { name: "Netapp, Inc", symbol: "NTAP" },
  { name: "American Water Works Company, Inc", symbol: "AWK" },
  { name: "Ameren Corporation", symbol: "AEE" },
  { name: "West Pharmaceutical Services, Inc.", symbol: "WST" },
  { name: "Ppl Corporation", symbol: "PPL" },
  { name: "On Semiconductor Corp", symbol: "ON" },
  { name: "Pultegroup, Inc.", symbol: "PHM" },
  { name: "Hubbell Incorporated", symbol: "HUBB" },
  { name: "The Hershey Company", symbol: "HSY" },
  { name: "Edison International", symbol: "EIX" },
  { name: "Expedia Group, Inc.", symbol: "EXPE" },
  { name: "Ptc, Inc", symbol: "PTC" },
  { name: "Kellanova", symbol: "K" },
  { name: "Teradyne, Inc.", symbol: "TER" },
  { name: "Cincinnati Financial Corp", symbol: "CINF" },
  { name: "Atmos Energy Corporation", symbol: "ATO" },
  { name: "Regions Financial Corp.", symbol: "RF" },
  { name: "Warner Bros. Discovery, Inc. Series a", symbol: "WBD" },
  { name: "Teledyne Technologies Incorporated", symbol: "TDY" },
  { name: "Western Digital Corp.", symbol: "WDC" },
  { name: "International Flavors & Fragrances Inc.", symbol: "IFF" },
  { name: "Darden Restaurants, Inc.", symbol: "DRI" },
  { name: "Coterra Energy Inc.", symbol: "CTRA" },
  { name: "Weyerhaeuser Company", symbol: "WY" },
  { name: "Sba Communications Corp", symbol: "SBAC" },
  { name: "Biogen Inc.", symbol: "BIIB" },
  { name: "Zimmer Biomet Holdings, Inc.", symbol: "ZBH" },
  { name: "Centerpoint Energy, Inc.", symbol: "CNP" },
  { name: "Packaging Corp of America", symbol: "PKG" },
  { name: "Live Nation Entertainment Inc.", symbol: "LYV" },
  { name: "Steris Plc", symbol: "STE" },
  { name: "Eversource Energy", symbol: "ES" },
  { name: "Leidos Holdings, Inc.", symbol: "LDOS" },
  { name: "Zebra Technologies Corporation", symbol: "ZBRA" },
  { name: "Cboe Global Markets, Inc.", symbol: "CBOE" },
  { name: "Nrg Energy, Inc.", symbol: "NRG" },
  { name: "Northern Trust Corp", symbol: "NTRS" },
  { name: "Citizens Financial Group, Inc.", symbol: "CFG" },
  { name: "Lennox International Inc.", symbol: "LII" },
  { name: "Firstenergy Corp.", symbol: "FE" },
  { name: "Southwest Airlines Co.", symbol: "LUV" },
  { name: "First Solar, Inc.", symbol: "FSLR" },
  { name: "Clorox Company", symbol: "CLX" },
  { name: "Labcorp Holdings Inc.", symbol: "LH" },
  { name: "Cms Energy Corporation", symbol: "CMS" },
  { name: "Lyondellbasell Industries N.v. Class A", symbol: "LYB" },
  { name: "International Paper Co.", symbol: "IP" },
  { name: "Seagate Technology Holdings Plcs", symbol: "STX" },
  { name: "Ulta Beauty, Inc.", symbol: "ULTA" },
  { name: "Insulet Corporation", symbol: "PODD" },
  { name: "Essex Property Trust, Inc", symbol: "ESS" },
  { name: "Mccormick & Company, Incorporated Non-Vtg Cs", symbol: "MKC" },
  { name: "Snap-on Incorporated", symbol: "SNA" },
  { name: "The Cooper Companies, Inc.", symbol: "COO" },
  { name: "Builders Firstsource, Inc.", symbol: "BLDR" },
  { name: "W.R. Berkley Corporation", symbol: "WRB" },
  { name: "Invitation Homes Inc.", symbol: "INVH" },
  { name: "Jabil Inc.", symbol: "JBL" },
  { name: "Mid-America Apartment Communities, Inc.", symbol: "MAA" },
  { name: "Trimble Inc.", symbol: "TRMB" },
  { name: "Steel Dynamics Inc", symbol: "STLD" },
  { name: "Keycorp", symbol: "KEY" },
  { name: "Verisign Inc", symbol: "VRSN" },
  { name: "The Estee Lauder Companies Inc. Class A", symbol: "EL" },
  { name: "Factset Research Systems", symbol: "FDS" },
  { name: "Nisource Inc.", symbol: "NI" },
  { name: "Quest Diagnostics Inc.", symbol: "DGX" },
  { name: "Molina Healthcare, Inc.", symbol: "MOH" },
  { name: "Jacobs Solutions Inc.", symbol: "J" },
  { name: "Principal Financial Group, Inc.", symbol: "PFG" },
  { name: "Pentair Plc", symbol: "PNR" },
  { name: "Omnicom Group Inc.", symbol: "OMC" },
  { name: "Cf Industries Holding, Inc.", symbol: "CF" },
  { name: "Masco Corporation", symbol: "MAS" },
  { name: "Hologic Inc", symbol: "HOLX" },
  { name: "Idex Corporation", symbol: "IEX" },
  { name: "Genuine Parts Company", symbol: "GPC" },
  { name: "Ball Corporation", symbol: "BALL" },
  { name: "Best Buy Company, Inc.", symbol: "BBY" },
  { name: "Tyson Foods, Inc.", symbol: "TSN" },
  { name: "Tapestry, Inc.", symbol: "TPR" },
  { name: "Baxter International Inc.", symbol: "BAX" },
  { name: "Las Vegas Sands Corp.", symbol: "LVS" },
  { name: "Expeditors International of Washington, Inc.", symbol: "EXPD" },
  { name: "Everest Group, Ltd.", symbol: "EG" },
  { name: "Super Micro Computer, Inc.", symbol: "SMCI" },
  { name: "Dollar General Corp.", symbol: "DG" },
  { name: "Alexandria Real Estate Equities, Inc.", symbol: "ARE" },
  { name: "Avery Dennison Corp.", symbol: "AVY" },
  { name: "Loews Corporation", symbol: "L" },
  { name: "F5, Inc.", symbol: "FFIV" },
  { name: "Kimco Realty Corp.", symbol: "KIM" },
  { name: "Alliant Energy Corporation", symbol: "LNT" },
  { name: "Align Technology Inc", symbol: "ALGN" },
  { name: "Gen Digital Inc.", symbol: "GEN" },
  { name: "Revvity, Inc.", symbol: "RVTY" },
  { name: "Skyworks Solutions Inc", symbol: "SWKS" },
  { name: "Textron, Inc.", symbol: "TXT" },
  { name: "Jb Hunt Transport Services Inc", symbol: "JBHT" },
  { name: "Aptiv Plc", symbol: "APTV" },
  { name: "Domino's Pizza Inc.", symbol: "DPZ" },
  { name: "Dollar Tree Inc.", symbol: "DLTR" },
  { name: "Evergy, Inc.", symbol: "EVRG" },
  { name: "Healthpeak Properties, Inc.", symbol: "DOC" },
  { name: "Viatris Inc.", symbol: "VTRS" },
  { name: "Amcor Plcs", symbol: "AMCR" },
  { name: "Akamai Technologies Inc", symbol: "AKAM" },
  { name: "Rollins, Inc.", symbol: "ROL" },
  { name: "Pool Corporation", symbol: "POOL" },
  { name: "Epam Systems, Inc.", symbol: "EPAM" },
  { name: "Stanley Black & Decker, Inc.", symbol: "SWK" },
  { name: "Juniper Networks Inc", symbol: "JNPR" },
  { name: "Henry (Jack) & Associates", symbol: "JKHY" },
  { name: "Conagra Brands, Inc.", symbol: "CAG" },
  { name: "Udr, Inc.", symbol: "UDR" },
  { name: "Carmax Inc.", symbol: "KMX" },
  { name: "C.H. Robinson Worldwide, Inc.", symbol: "CHRW" },
  { name: "Host Hotels & Resorts, Inc.", symbol: "HST" },
  { name: "Camden Property Trust", symbol: "CPT" },
  { name: "Bio-Techne Corp.", symbol: "TECH" },
  { name: "Moderna, Inc.", symbol: "MRNA" },
  { name: "Regency Centers Corporation", symbol: "REG" },
  { name: "Incyte Genomics Inc", symbol: "INCY" },
  { name: "Norwegian Cruise Line Holdings Ltd.s", symbol: "NCLH" },
  { name: "Bunge Global Sa", symbol: "BG" },
  { name: "Allegion Public Limited Company", symbol: "ALLE" },
  { name: "Nordson Corp", symbol: "NDSN" },
  { name: "Dayforce, Inc.", symbol: "DAY" },
  { name: "Albemarle Corporation", symbol: "ALB" },
  { name: "The J.M. Smucker Company", symbol: "SJM" },
  { name: "Universal Health Services, Inc. Class B", symbol: "UHS" },
  { name: "Fox Corporation Class A", symbol: "FOXA" },
  { name: "Eastman Chemical Company", symbol: "EMN" },
  { name: "Assurant, Inc.", symbol: "AIZ" },
  { name: "News Corporation Class A", symbol: "NWSA" },
  { name: "Bxp, Inc.", symbol: "BXP" },
  { name: "The Interpublic Group of Companies, Inc.", symbol: "IPG" },
  { name: "Erie Indemnity Co", symbol: "ERIE" },
  { name: "Paycom Software, Inc.", symbol: "PAYC" },
  { name: "Solventum Corporation", symbol: "SOLV" },
  { name: "Lkq Corporation", symbol: "LKQ" },
  { name: "Globe Life Inc.", symbol: "GL" },
  { name: "Generac Holdings Inc", symbol: "GNRC" },
  { name: "Ralph Lauren Corporation", symbol: "RL" },
  { name: "Pinnacle West Capital Corporation", symbol: "PNW" },
  { name: "Molson Coors Beverage Company Class B", symbol: "TAP" },
  { name: "Apa Corporation", symbol: "APA" },
  { name: "Charles River Laboratories International, Inc.", symbol: "CRL" },
  { name: "Henry Schein Inc", symbol: "HSIC" },
  { name: "Enphase Energy, Inc.", symbol: "ENPH" },
  { name: "Walgreens Boots Alliance, Inc", symbol: "WBA" },
  { name: "Hormel Foods Corporation", symbol: "HRL" },
  { name: "The Mosaic Company", symbol: "MOS" },
  { name: "Lamb Weston Holdings, Inc.", symbol: "LW" },
  { name: "A.O. Smith Corporation", symbol: "AOS" },
  { name: "Aes Corporation", symbol: "AES" },
  { name: "Teleflex Incorporated", symbol: "TFX" },
  { name: "Marketaxess Holdings Inc.", symbol: "MKTX" },
  { name: "Match Group, Inc", symbol: "MTCH" },
  { name: "Federal Realty Investment Trust", symbol: "FRT" },
  { name: "Celanese Corporation", symbol: "CE" },
  { name: "Huntington Ingalls Industries, Inc.", symbol: "HII" },
  { name: "The Campbell's Company", symbol: "CPB" },
  { name: "Wynn Resorts Ltd", symbol: "WYNN" },
  { name: "Mgm Resorts International", symbol: "MGM" },
  { name: "Invesco Ltd", symbol: "IVZ" },
  { name: "Hasbro, Inc.", symbol: "HAS" },
  { name: "Davita Inc.", symbol: "DVA" },
  { name: "Caesars Entertainment, Inc.", symbol: "CZR" },
  { name: "Borgwarner Inc.", symbol: "BWA" },
  { name: "Fmc Corporation", symbol: "FMC" },
  { name: "Mohawk Industries, Inc.", symbol: "MHK" },
  { name: "Paramount Global Class B", symbol: "PARA" },
  { name: "Brown-Forman Corporation Class B", symbol: "BF.B" },
  { name: "Fox Corporation Class B", symbol: "FOX" },
  { name: "Franklin Resources, Inc.", symbol: "BEN" },
  { name: "News Corporation Class B", symbol: "NWS" },
];
